### ISSUE TITLE
Specific songs[request]

### ISSUE THREAD

**Issue by Anoaxx** [sf-inc/music_control#10]
This mod is named "music control" but you can specify what specific songs can play or what can't. Can you add option to do it?

**Comment by charlyb01** [comment]
I was thinking about that recently but this will need lot of work. Stay tuned!

**Comment by charlyb01** [comment]
I guess I won't be able to do this until I found out how to play specific songs, just like for thsese: Play previous song, and Repeat song. I'll keep searching but I may release a new version before these changes

**Comment by charlyb01** [comment]
Hi, I won't have time to add this new feature for now because I got a lot of works. I'll try to update it before 1.18 but not so sure, I'm sorry. But I won't forget you ;)

**Comment by charlyb01** [comment]
I know it has been a while, but I'm finally working on it!
It should come in the next mod update, next month I guess =)

**Comment by Anoaxx** [comment]
> I know it has been a while, but I'm finally working on it! It should come in the next mod update, next month I guess =)

Yeeeey! <3

**Comment by charlyb01** [comment]
Oh wait I thought this issue was play a specific song but it's actually being able to choose what can be played!
Well only one part is done, sorry. The rest is not done yet

**Comment by charlyb01** [comment]
I hope you gonna love it! In my opinion, it's amazing 😃
