### ISSUE TITLE
Music controls on survival[request]

### ISSUE THREAD

**Issue by Anoaxx** [sf-inc/music_control#11]
_PROBLEM_

Sometimes i wanna skip song, but i still wanna don't override from what poll songs are played on. Because if i understand correctly i cant pick dynamic music like playing in vanilla with changing dimensions etc. and this will be helpful if someone have resource pack

**Comment by charlyb01** [comment]
This mod override a few things for now. For example, musics playing underwater only is now able to play whenever you're in overworld category. To my mind, it's not a big deal as these specific songs are too specific and may rarely play. However, songs have still their weight: meaning that one that is more common in vanilla will be more common with the mod too. Also, when changing dimensions, it will automatically change category if you didn't allow cheat.
I'm not going to change this behavior for now, unless I find a better idea. But when #10 will be done, it will at least be better than now I hope =)
