### ISSUE TITLE
Category "Vanilla" or "Default"[request]

### ISSUE THREAD

**Issue by Anoaxx** [sf-inc/music_control#12]
_PROBLEM_
when im using music controls im not able to play songs like in vanilla(dynamicaly change depends on dimension or resource pack). So i kindly ask you to add or restore this feature to music player. Im talking about player you have on creative/cheated survival. Or i misunderstood something and "all" category work that way. Then change name to Vanilla or Default, and set it as default category to play. 

If you do this you can do "survival cheat" turn on by default.

**Comment by charlyb01** [comment]
As said in the previous issue, it does change dynamically categories when changing dimensions if you're not in cheat mode. Feel free to ask again in a different way, I may have not understood the problem.
For the second part, ALL category is just a category that allows you to play any music detected by the game (musics only, not every sound!). So this is not the default behavior of Minecraft. But adding a DEFAULT category that restore the way vanilla minecraft musics are played is a good idea, I'll add this ;)
