### ISSUE TITLE
Advanced music player[request]

### ISSUE THREAD

**Issue by Anoaxx** [sf-inc/music_control#13]
If you can do then please separate options to change categories and music player to be turn on/off separately.

**Comment by charlyb01** [comment]
I don't understand. Do you talk about about a default category (previous issue)?
Or are you saying that you would prefer not to have this category but a more direct way to enable/disable these categories?

**Comment by Anoaxx** [comment]
what im saying is... player controls such like skip or pause/resume needs to be separate with changing categories. Like i don't wanna accidentaly change category when i wanna skip song etc. just change this options to turn on/off separately. Specially in survival mode.

**Comment by charlyb01** [comment]
If I understand, you just want to change the keybinding? You can do that in the game menu

**Comment by Anoaxx** [comment]
Im closing this. Better way to do this is on #14
