### ISSUE TITLE
Incorrect song names

### ISSUE THREAD

**Issue by Qendolin** [sf-inc/music_control#18]
When a resource pack overwrites the default music the mod still shows vanilla track names. Please detect when a track is changed by a resource pack and either get the song name from the music file's metadata or display nothing at all.

**Comment by charlyb01** [comment]
Hi, thanks for the report! Actually, I thought that replacing minecraft musics with a resource pack would display the right name if we set the name in the lang file but it seems not. I'll see what I can do ;)

**Comment by EGOIST1372** [comment]
@charlyb01 Hi there is also these wrong name that I get from nether. I have no custom music or resources so idk what causing it
![image](https://user-images.githubusercontent.com/86555131/171179857-a0e00439-9147-44d2-869a-070c14171a76.png)

**Comment by charlyb01** [comment]
Hello, I checked this issue again and actually it works. Of course, if you don't set your own language file to update the name of the music, I won't update the displayed name, as I told you. But you can add a lang file with the updated name. I think it has always work, but I tried without thinking too much, so anyway it works. What you could do wrong when doing this, is to set the lang file inside the same namespace, which is minecraft when you override its music. However, it must be set in a new directory/namespace as music translation is not vanilla, in `music_control`. 

So, a resource pack overriding minecraft music could look like:
* myresourcepack/assets/
  * minecraft/
    * sounds/music/
      * other music directories
      * music files
  * music_control/
    * lang/
      * en_us.json
