### ISSUE TITLE
it freezes when a new song plays

### ISSUE THREAD

**Issue by EGOIST1372** [sf-inc/music_control#19]
it freezes couple seconds when a new song plays when the previous song ends by its own
doesn't happen when i switch songs
and sometimes when a music starts after a few seconds it changes to the next song even though the song is not finished yet

**Comment by EGOIST1372** [comment]
latest version 1.18.1
and i can confirm after i removed the mod after music changed by its own didn't had any freeze problem

**Comment by EGOIST1372** [comment]
it seems it got fix after i removed the other music mod that i had
its all cool now

**Comment by EGOIST1372** [comment]
BTW does your mod changes the vanilla way of choosing music in certain scenarios ?
like when i go underwater it changes to a specific song so if i use this mod and change for instance music when I'm on land does this mean minecraft not gonna change it when I'm under water anymore?
and also if you want to solve the compatibility issue with my other music mod here is the [link](https://www.curseforge.com/minecraft/mc-mods/infinite-music)

**Comment by EGOIST1372** [comment]
you might ask why i use both mod together, well the other mod has the ability to change song even when I'm in title screen but with your mod its more convenient in-game to use and more feature rich :)

**Comment by charlyb01** [comment]
> BTW does your mod changes the vanilla way of choosing music in certain scenarios ?
like when i go underwater it changes to a specific song so if i use this mod and change for instance music when I'm on land does this mean minecraft not gonna change it when I'm under water anymore?
If you're not in the DEFAULT category, yes it is the purpose of the other categories. It will be changed and improved in the future but not right now.

> and also if you want to solve the compatibility issue with my other music mod here is the [link](https://www.curseforge.com/minecraft/mc-mods/infinite-music)
I don't have time for this at the moment,  sorry

**Comment by EGOIST1372** [comment]
no worries about the incompatibility since both mods have same purpose and your mod have more features so I deleted the other mod and it's all good
thanks

**Comment by EGOIST1372** [comment]
also since you adding new features to v1.6 , it would be great add the ability to change the music in title screen as well
