### ISSUE TITLE
[Suggestion] Allow music control in menu

### ISSUE THREAD

**Issue by barraIhsan** [sf-inc/music_control#2]
So this is simple, now you can press the hotkey in menu to change the music

**Comment by charlyb01** [comment]
Even though the idea is good, it's literally impossible without a huge modification. Indeed, hotkeys are not handled in menu so I should add a way to interact with keyboard in the menu and I'm not planning to make this, sorry :/

**Comment by barraIhsan** [comment]
Oh, or maybe there is a button between the fabric version and the copyright
![image](https://user-images.githubusercontent.com/57800056/113378106-5e3c6980-93a0-11eb-90bf-650193420bed.png)
So there is 5 button and the print music is above the button

**Comment by charlyb01** [comment]
I also won't add button on menu, sorry
