### ISSUE TITLE
Add support for atmosfera and charmonium

### ISSUE THREAD

**Issue by EGOIST1372** [sf-inc/music_control#24]
haven't tried charmonium but with atmosfera it just doesn't change music because atmosfera have let's say 2 music for this kinda biome and when its not playing or even playing changing music just repeats that music or musics that atmosfera set and there are no vanilla musics anymore ;-;
https://www.curseforge.com/minecraft/mc-mods/atmosfera (atmosfera updated to 1.19 in github [here](https://github.com/Haven-King/Atmosfera/issues/36#issuecomment-1162199930))
https://www.curseforge.com/minecraft/mc-mods/charmonium

**Comment by charlyb01** [comment]
With the new system incoming in the next update, this shouldn't happen anymore.
Please let me know of it still happens in the future when next version is out by reopening it
