### ISSUE TITLE
crash on pixelmon mod

### ISSUE THREAD

**Issue by alph312a** [sf-inc/music_control#26]
i go intro battle then when battle end its crash my game i hear sound from battle and from the mod on same time before its crash
(used own Sound Ressource pack to replace orginal music)
https://streamable.com/mctzu7
[crash-2022-05-26_16.05.35-client.txt](https://github.com/sf-inc/music_control/files/10230726/crash-2022-05-26_16.05.35-client.txt)

**Comment by charlyb01** [comment]
Hello,
It seems you're using Minecraft Forge mod loader, but all my mods are Fabric only. I'm sorry for the inconvenience.

**Comment by alph312a** [comment]
why all good music controll things only for fabric :( that so bruh
just found one that work with forge but that has no hotkeys to skip current song :(
