### ISSUE TITLE
Saving config doesn't save my config

### ISSUE THREAD

**Issue by 1schlick** [sf-inc/music_control#27]
I spent hours configuring all my music, and then I clicked the button "save config". The screen reloaded, and then I checked my configs to see if they were the same. AND THEY WERE JUST REVERTED BACK TO THE DEFAULTS.

Edit: Nevermind I figured out how to prevent that from happening.

**Comment by charlyb01** [comment]
It's always a pleasure to help, but this would be even better if you would not shout out that this mod is a scam.
Then, I would like to know if you selected the resource pack in your list, **as written in the description**. If not, it won't work, but your work **will not be lost**. Indeed, saving should save your work. I just didn't figure out how to select the resource pack automatically for now.
If it wasn't your problem, I would like to know how you prevented that. The mod may have bugs, just like any mod. And it's even more likely when you're playing with a mod in beta. Feel free to share any issue you encounter, and I'll be glad to help again =)

**Comment by charlyb01** [comment]
> If it wasn't your problem, I would like to know how you prevented that.

I would be pleased if you let me know :)

**Comment by 1schlick** [comment]
All I had to do was just load the resource pack.
