### ISSUE TITLE
Biome-specific music doesn't work in creative

### ISSUE THREAD

**Issue by 1schlick** [sf-inc/music_control#28]
The default creative mode music is Taswell, Biome Fest, Blind Spots, Dreiton, Aria Math, Haunt Muskie, and Floating Dream. Normally the game cycles through all these musics.

I go to a beach biome, and open up the music config, and add the song Ward to the beach biome.

<img width="771" alt="Screen Shot 2023-01-05 at 1 18 41 PM" src="https://user-images.githubusercontent.com/53189655/210881840-5ee9a886-15d1-4788-9c86-39e84bd7f020.png">

Now the expected behavior is that the song Ward should play when I am in a beach biome. But that is not what happens. Instead, the game just cycles through the creative mode music. This can be quickly tested by using the "next music" hotkey until the pattern repeats many times. You can also look at the last played music list to see which musics have been playing. As you can see, only the creative music has played and the song Ward has not played at all.

<img width="769" alt="Screen Shot 2023-01-05 at 12 52 14 PM" src="https://user-images.githubusercontent.com/53189655/210877744-91a1e676-d7a0-49dd-a8e3-2a2002ed252d.png">
<img width="770" alt="Screen Shot 2023-01-05 at 12 52 23 PM" src="https://user-images.githubusercontent.com/53189655/210877773-74ec313d-a33d-4ddd-a3d6-9a3faa81f9a0.png">

I tried to see if the beach music could play at all, by removing the creative music altogether.

<img width="780" alt="Screen Shot 2023-01-05 at 1 00 30 PM" src="https://user-images.githubusercontent.com/53189655/210879036-b050ae6a-e8c0-490f-bb87-d25241d7812d.png">

Now, the game falls back to the "game" music, which consists of Comforting Memories, Haggstrom, Left to Bloom, Minecraft, Clark, Living Mice, Dry Hands, Oxygene, One More Day, Wet Hands, Mice on Venus, Key, Subwoofer Lullaby, Danny, Sweden, and Floating Dream. Yet again, the song Ward doesn't play at all despite me being in a beach biome.

<img width="769" alt="Screen Shot 2023-01-05 at 1 08 41 PM" src="https://user-images.githubusercontent.com/53189655/210880301-5b40595e-c7c8-44fe-85ea-1eb2d9482ec9.png">

<img width="770" alt="Screen Shot 2023-01-05 at 1 08 54 PM" src="https://user-images.githubusercontent.com/53189655/210880323-ee14d1ad-e3cd-455b-91a7-538c0c484774.png">

<img width="770" alt="Screen Shot 2023-01-05 at 1 09 04 PM" src="https://user-images.githubusercontent.com/53189655/210880353-3915a44f-fd31-45c3-b449-c9cf2e1d7652.png">

<img width="770" alt="Screen Shot 2023-01-05 at 1 09 12 PM" src="https://user-images.githubusercontent.com/53189655/210880375-8e2523d3-20a4-46cf-8b15-e785f0b926da.png">

I attempt to fix the issue by removing all "game" music, so that way the only song available to be played is the song Ward.

<img width="770" alt="Screen Shot 2023-01-05 at 1 11 37 PM" src="https://user-images.githubusercontent.com/53189655/210880787-8edebdce-2274-4224-b7cc-d01391719a0f.png">

And to my dismay, the message that I receive is "Now Playing: meta:missing_sound."

![2023-01-05_13 12 40](https://user-images.githubusercontent.com/53189655/210881122-0dd651a8-0f76-424b-9dab-34153e1d5e16.png)

What this means is that the biome-specific music feature is not working at all. The game isn't acknowledging the biome-specific music, and only looks at the creative and game music lists when deciding what music to play. At least, this is how it is in the overworld. I did test this in the Nether and biome-specific music seems to work perfectly, probably because there is no creative and game music in the Nether.

**Comment by charlyb01** [comment]
Hello, thanks for the report.
It does work, but for now in creative you get only creative music. I may add an option to use biome specific music in the next update if you're interested =)

**Comment by 1schlick** [comment]
It doesn't work in survival either. By default, the "game" music plays. Here I've set the game music to include only the song "Minecraft."

<img width="616" alt="Screen Shot 2023-01-06 at 4 46 21 PM" src="https://user-images.githubusercontent.com/53189655/211122954-897ee98f-afa1-42e5-8c4a-404f861ed7b3.png">

I add a custom song, "Gerudo Valley" to the desert biome, then I go to a desert biome.

<img width="853" alt="Screen Shot 2023-01-06 at 4 46 42 PM" src="https://user-images.githubusercontent.com/53189655/211122984-81450439-b565-4568-a4a2-71a286d81d9c.png">

If I cycle through the music with the "Next Music" hotkey, then only "Minecraft" plays.

<img width="616" alt="Screen Shot 2023-01-06 at 4 47 56 PM" src="https://user-images.githubusercontent.com/53189655/211123062-494bce29-7a53-4ab0-b4cc-74ba12a0efe3.png">

Now I remove the song "Minecraft" from the "Game" music, so that there is no "game" music.

<img width="617" alt="Screen Shot 2023-01-06 at 4 48 47 PM" src="https://user-images.githubusercontent.com/53189655/211123115-e667445d-2192-445b-a931-fb49fa6e6257.png">

Now the expected behavior is that the game should play the biome-specific music for the current biome. But instead, this happens:

![2023-01-06_16 49 42](https://user-images.githubusercontent.com/53189655/211123214-d17b59c9-2187-48c5-9027-d3e31293fa22.png)

How do I get the biome-specific music to play?

**Comment by 1schlick** [comment]
By the way I am using beta 1.19.3

**Comment by charlyb01** [comment]
Make sure you're in a desert, please check with F3. Also, you should have your config saved and loaded via the resource pack.
I'm gonna do some more testing but the expacted behavior worked for me until now. If it still doesn't work for you, please give me more detailed steps to reproduce.
Also, you should not empty Game event as it's the music that will play if some biome is not properly set.

**Comment by EGOIST1372** [comment]
@charlyb01 any new on this issue?
thanks in advance <3

**Comment by charlyb01** [comment]
I didn't do anything about it for now, I got stuck with the 1.19.3 issue. I will do this right after.
