### ISSUE TITLE
Music doesn't play in the End

### ISSUE THREAD

**Issue by 1schlick** [sf-inc/music_control#29]
Whether it's default music or custom music, music simply doesn't play when you're in the End with this mod enabled.

**Comment by charlyb01** [comment]
If you're using releases version of the mod, it's a I known issue. You can play music in default mod only.
If you're using the beta version, let me know. I will check what's wrong.

**Comment by 1schlick** [comment]
I am using the beta for 1.19.3

**Comment by charlyb01** [comment]
Confirmed in beta versions, I'm working on it
