### ISSUE TITLE
Double music

### ISSUE THREAD

**Issue by barraIhsan** [sf-inc/music_control#3]
sometimes when you change the music too fast, the music like twice play so I have to `/stopsound` or using the Left arrow to pause.

**Comment by charlyb01** [comment]
Oh I didn't know about it! I'll check this out, thanks for the report ;)

**Comment by barraIhsan** [comment]
What? I often have this issue, or maybe because I paly music, I pause it I play it and I changed it very fast?

**Comment by charlyb01** [comment]
I tried to spam every key and I never had this problem. This is either caused by what I said in my previous message, or a problem from another mod
