### ISSUE TITLE
In 1.17.1, impossible to open GUI

### ISSUE THREAD

**Issue by 1schlick** [sf-inc/music_control#30]
The curseforge page says that the key "M" opens the GUI. But I tested it and it doesn't do anything. I go into Minecraft's controls to see if I can configure the key, and there is no such option to configure the GUI.

<img width="1440" alt="Screen Shot 2023-01-10 at 11 12 32 PM" src="https://user-images.githubusercontent.com/53189655/211741019-f65d7f33-76b4-4431-8337-3e105ce9cb4a.png">

How do I open the GUI?

**Comment by charlyb01** [comment]
This feature is a beta feature, available only on last beta version. Older versions doesn't have the same system. See [changelog](https://github.com/sf-inc/music_control/blob/main/CHANGELOG.md). Current [README](https://github.com/sf-inc/music_control/blob/main/README.md) describes you old versions of the mod.

**Comment by 1schlick** [comment]
Any chance you could update the mod for 1.17.1 to have this feature?

**Comment by charlyb01** [comment]
No chance I will, sorry. This would take too much of my time, and I already don't have much time to put into modding. But if anyone wants to do the backport, I'll be happy review it

**Comment by 1schlick** [comment]
Does biome-specific music work in 1.17.1 as long as I make the resource pack myself? Or is that feature something that only comes with the GUI in later versions of the mod?
