### ISSUE TITLE
"Subwoofer Lullaby" typo

### ISSUE THREAD

**Issue by palaceswitcher** [sf-inc/music_control#35]
Subwoofer Lullaby is mistakenly titled "Subwoofer Lubally".
![image](https://github.com/sf-inc/music_control/assets/60408182/a9b8aa16-4ba0-4c06-8553-0235770fb2a1)

**Comment by charlyb01** [comment]
Hello, thank you for the report! That's a funny one, I didn't notice ^^  
I will update it and release a new version soon with a few other minor changes
