### ISSUE TITLE
Crashing the game

### ISSUE THREAD

**Issue by EGOIST1372** [sf-inc/music_control#36]
latest 1.20.1 version from modrinth
and this is the error i get

```

Time: 2023-08-14 07:07:45
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.equals(Object)" because "this.field_5448" is null
	at net.minecraft.class_1102.method_4783(class_1102.java:42)
	at net.minecraft.class_1140.method_4854(class_1140.java:365)
	at net.minecraft.class_1144.method_4873(class_1144.java:248)
	at net.minecraft.class_1142.handler$dja000$music_control$playMusic(class_1142.java:1612)
	at net.minecraft.class_1142.method_4858(class_1142.java)
	at net.minecraft.class_1142.method_18669(class_1142.java:44)
	at net.minecraft.class_310.method_1574(class_310.java:1909)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1102.method_4783(class_1102.java:42)
	at net.minecraft.class_1140.method_4854(class_1140.java:365)
	at net.minecraft.class_1144.method_4873(class_1144.java:248)
	at net.minecraft.class_1142.handler$dja000$music_control$playMusic(class_1142.java:1612)
	at net.minecraft.class_1142.method_4858(class_1142.java)
	at net.minecraft.class_1142.method_18669(class_1142.java:44)
Mixins in Stacktrace:
	net.minecraft.class_1140:
		de.keksuccino.auudio.mixin.client.IMixinSoundEngine (auudio.mixin.json)
		com.sonicether.soundphysics.mixin.SoundSystemMixin (sound_physics_remastered.mixins.json)
		com.github.charlyb01.music_control.mixin.SoundSystemMixin (music_control.mixins.json)
		net.fabricmc.fabric.mixin.client.sound.SoundSystemMixin (fabric-sound-api-v1.mixins.json)
		eu.ha3.presencefootsteps.mixins.MSoundSystem (presencefootsteps.mixin.json)
		de.keksuccino.auudio.mixin.client.MixinSoundEngine (auudio.mixin.json)
	net.minecraft.class_1144:
		com.github.charlyb01.music_control.mixin.SoundManagerMixin (music_control.mixins.json)
		de.keksuccino.auudio.mixin.client.IMixinSoundManager (auudio.mixin.json)
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.client.mixins.json)
	net.minecraft.class_1142:
		com.github.charlyb01.music_control.mixin.MusicTrackerMixin (music_control.mixins.json)
		de.keksuccino.fancymenu.mixin.client.MixinMusicManager (fancymenu.general.mixin.json)
		de.keksuccino.fmaudio.mixin.client.MixinMusicManager (fmaudio.mixin.json)

-- Affected level --
Details:
	All players: 1 total; [class_746[''/560024, l='ClientLevel', x=641.24, y=67.00, z=1297.63]]
	Chunk stats: 1024, 453 F: 179 L: 3593 U: 1
	Level dimension: minecraft:overworld
	Level spawn location: World: (-35,74,-39), Section: (at 13,10,9 in -3,4,-3; chunk contains blocks -48,-64,-48 to -33,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 60222729 game time, 74026804 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace:
	net.minecraft.class_638:
		net.fabricmc.fabric.mixin.event.lifecycle.client.ClientWorldMixin (fabric-lifecycle-events-v1.client.mixins.json)
		dev.architectury.mixin.fabric.client.MixinClientLevel (architectury.mixins.json)
		ca.spottedleaf.starlight.mixin.client.world.ClientLevelMixin (starlight.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.world.map.ClientWorldMixin (sodium.mixins.json)
		de.johni0702.minecraft.bobby.mixin.ClientWorldAccessor (bobby.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.world.biome.ClientWorldMixin (sodium.mixins.json)
		dev.hephaestus.atmosfera.mixin.MixinClientWorld (atmosfera.mixins.json)
		dev.tr7zw.entityculling.mixin.ClientWorldMixin (entityculling.mixins.json)
		dlovin.inventoryhud.mixin.UpdateNotifierMixin (inventoryhud.mixins.json)
		me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ClientWorldMixin (lithium.mixins.json)
		net.coderbot.iris.mixin.vertices.block_rendering.MixinClientLevel (mixins.iris.vertexformat.json)
		me.steinborn.krypton.mixin.client.fastchunkentityaccess.ClientWorldMixin (krypton.mixins.json)
		dev.onyxstudios.cca.mixin.entity.client.MixinClientWorld (mixins.cardinal_components_entity.json)
		dev.tr7zw.itemswapper.mixin.ClientLevelMixin (itemswapper.mixins.json)
	net.minecraft.class_310:
		com.blamejared.ambientenvironment.mixin.MixinMinecraft (ambientenvironment.fabric.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		com.anthonyhilyard.prism.mixin.MinecraftMixin (prism.mixins.json)
		dev.stashy.extrasounds.mixin.hotbar.MinecraftClientMixin (extrasounds.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinMinecraft (konkrete.mixin.json)
		fuzs.forgeconfigapiport.mixin.client.MinecraftMixin (forgeconfigapiport.common.mixins.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin2 (optigui.mixins.json)
		dev.stashy.extrasounds.mixin.inventory.MinecraftClientMixin (extrasounds.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.client.MixinMinecraft (drippyloadingscreen.mixin.json)
		opekope2.optigui.mixin.MinecraftClientMixin (optigui.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (mixins.blur.json)
		dlovin.inventoryhud.mixin.PlayerMixin (inventoryhud.mixins.json)
		fi.dy.masa.minihud.mixin.MixinMinecraftClient (mixins.minihud.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.client.IMixinMinecraft (drippyloadingscreen.mixin.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		io.github.cottonmc.cotton.gui.impl.mixin.client.MinecraftClientMixin (mixins.libgui.json)
		de.maxhenkel.peek.mixin.MinecraftMixin (peek.mixins.json)
		de.johni0702.minecraft.bobby.mixin.MinecraftClientMixin (bobby.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		dev.hephaestus.atmosfera.mixin.MinecraftClientMixin (atmosfera.mixins.json)
		de.maxhenkel.status.mixin.MinecraftMixin (status.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		net.xolt.freecam.mixins.MinecraftClientMixin (freecam.mixins.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.fabric.mixins.json)
		dynamicfps.mixin.MinecraftClientMixin (dynamicfps.mixins.json)
		de.keksuccino.auudio.mixin.client.MixinMinecraft (auudio.mixin.json)
		draylar.omegaconfig.mixin.ClientMixin (omega-config.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		org.anti_ad.mc.ipnext.mixin.MixinMinecraftClient (mixins.ipnext.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		com.minelittlepony.common.mixin.MixinMinecraftClient (kirin.mixin.json)
		de.guntram.mcmod.clickthrough.mixins.ItemUseMixin (mixins.clickthrough.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
		de.keksuccino.fancymenu.mixin.client.MixinMinecraft (fancymenu.general.mixin.json)
		obro1961.chatpatches.mixin.MinecraftClientMixin (chatpatches.mixins.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json)
		dzwdz.chat_heads.mixin.MinecraftMixin (chat_heads.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (sodium.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		io.grayray75.mods.fpsdisplay.mixin.MinecraftClientAccessor (fpsdisplay.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		de.keksuccino.fancymenu.mixin.client.IMixinMinecraft (fancymenu.general.mixin.json)
		com.glisco.isometricrenders.mixin.MinecraftClientMixin (isometric-renders.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		dev.tr7zw.itemswapper.mixin.MinecraftMixin (itemswapper.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
	net.minecraft.client.main.Main:
		link.infra.screenshotclipboard.common.mixin.AWTHackMixin (screenshotclipboard-common.mixins.json)
```

**Comment by EGOIST1372** [comment]
slightly different crash log when cycling through musics with forward arrow key

`Time: 2023-08-14 16:27:53
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.equals(Object)" because "this.field_5448" is null
	at net.minecraft.class_1102.method_4783(class_1102.java:42)
	at net.minecraft.class_1140.method_4854(class_1140.java:365)
	at net.minecraft.class_1144.method_4873(class_1144.java:248)
	at net.minecraft.class_1142.handler$djb000$music_control$playMusic(class_1142.java:1612)
	at net.minecraft.class_1142.method_4858(class_1142.java)
	at net.minecraft.class_1142.handleNextMusicKey(class_1142.java:1701)
	at net.minecraft.class_1142.handler$djb000$music_control$handleMusic(class_1142.java:1625)
	at net.minecraft.class_1142.method_18669(class_1142.java)
	at net.minecraft.class_310.method_1574(class_310.java:1909)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1102.method_4783(class_1102.java:42)
	at net.minecraft.class_1140.method_4854(class_1140.java:365)
	at net.minecraft.class_1144.method_4873(class_1144.java:248)
	at net.minecraft.class_1142.handler$djb000$music_control$playMusic(class_1142.java:1612)
	at net.minecraft.class_1142.method_4858(class_1142.java)
	at net.minecraft.class_1142.handleNextMusicKey(class_1142.java:1701)
	at net.minecraft.class_1142.handler$djb000$music_control$handleMusic(class_1142.java:1625)
	at net.minecraft.class_1142.method_18669(class_1142.java)
Mixins in Stacktrace:
	net.minecraft.class_1140:
		de.keksuccino.auudio.mixin.client.IMixinSoundEngine (auudio.mixin.json)
		eu.ha3.presencefootsteps.mixins.MSoundSystem (presencefootsteps.mixin.json)
		com.github.charlyb01.music_control.mixin.SoundSystemMixin (music_control.mixins.json)
		net.fabricmc.fabric.mixin.client.sound.SoundSystemMixin (fabric-sound-api-v1.mixins.json)
		com.sonicether.soundphysics.mixin.SoundSystemMixin (sound_physics_remastered.mixins.json)
		de.keksuccino.auudio.mixin.client.MixinSoundEngine (auudio.mixin.json)
	net.minecraft.class_1144:
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.client.mixins.json)
		com.github.charlyb01.music_control.mixin.SoundManagerMixin (music_control.mixins.json)
		de.keksuccino.auudio.mixin.client.IMixinSoundManager (auudio.mixin.json)
	net.minecraft.class_1142:
		com.github.charlyb01.music_control.mixin.MusicTrackerMixin (music_control.mixins.json)
		de.keksuccino.fancymenu.mixin.client.MixinMusicManager (fancymenu.general.mixin.json)
		de.keksuccino.fmaudio.mixin.client.MixinMusicManager (fmaudio.mixin.json)

-- Affected level --
Details:
	All players: 1 total; [class_746['EGOIST23'/738144, l='ClientLevel', x=649.76, y=68.00, z=1304.40]]
	Chunk stats: 1024, 453 F: 2913 L: 0 U: 66
	Level dimension: minecraft:overworld
	Level spawn location: World: (-35,74,-39), Section: (at 13,10,9 in -3,4,-3; chunk contains blocks -48,-64,-48 to -33,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 60891818 game time, 74869638 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace:
	net.minecraft.class_638:
		dev.architectury.mixin.fabric.client.MixinClientLevel (architectury.mixins.json)
		dev.tr7zw.entityculling.mixin.ClientWorldMixin (entityculling.mixins.json)
		dev.onyxstudios.cca.mixin.entity.client.MixinClientWorld (mixins.cardinal_components_entity.json)
		me.jellysquid.mods.sodium.mixin.core.world.biome.ClientWorldMixin (sodium.mixins.json)
		dev.hephaestus.atmosfera.mixin.MixinClientWorld (atmosfera.mixins.json)
		de.johni0702.minecraft.bobby.mixin.ClientWorldAccessor (bobby.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.world.map.ClientWorldMixin (sodium.mixins.json)
		me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ClientWorldMixin (lithium.mixins.json)
		dlovin.inventoryhud.mixin.UpdateNotifierMixin (inventoryhud.mixins.json)
		me.steinborn.krypton.mixin.client.fastchunkentityaccess.ClientWorldMixin (krypton.mixins.json)
		ca.spottedleaf.starlight.mixin.client.world.ClientLevelMixin (starlight.mixins.json)
		net.coderbot.iris.mixin.vertices.block_rendering.MixinClientLevel (mixins.iris.vertexformat.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.ClientWorldMixin (fabric-lifecycle-events-v1.client.mixins.json)
		dev.tr7zw.itemswapper.mixin.ClientLevelMixin (itemswapper.mixins.json)
	net.minecraft.class_310:
		com.blamejared.ambientenvironment.mixin.MixinMinecraft (ambientenvironment.fabric.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin2 (optigui.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin (optigui.mixins.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.fabric.mixins.json)
		dev.tr7zw.itemswapper.mixin.MinecraftMixin (itemswapper.mixins.json)
		fi.dy.masa.minihud.mixin.MixinMinecraftClient (mixins.minihud.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (mixins.blur.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.client.IMixinMinecraft (drippyloadingscreen.mixin.json)
		de.keksuccino.fancymenu.mixin.client.IMixinMinecraft (fancymenu.general.mixin.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.client.MixinMinecraft (drippyloadingscreen.mixin.json)
		fuzs.forgeconfigapiport.mixin.client.MinecraftMixin (forgeconfigapiport.common.mixins.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json)
		io.grayray75.mods.fpsdisplay.mixin.MinecraftClientAccessor (fpsdisplay.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		dev.hephaestus.atmosfera.mixin.MinecraftClientMixin (atmosfera.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinMinecraft (konkrete.mixin.json)
		dynamicfps.mixin.MinecraftClientMixin (dynamicfps.mixins.json)
		com.anthonyhilyard.prism.mixin.MinecraftMixin (prism.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		de.keksuccino.auudio.mixin.client.MixinMinecraft (auudio.mixin.json)
		com.glisco.isometricrenders.mixin.MinecraftClientMixin (isometric-renders.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		io.github.cottonmc.cotton.gui.impl.mixin.client.MinecraftClientMixin (mixins.libgui.json)
		dev.stashy.extrasounds.mixin.inventory.MinecraftClientMixin (extrasounds.mixins.json)
		draylar.omegaconfig.mixin.ClientMixin (omega-config.mixins.json)
		com.minelittlepony.common.mixin.MixinMinecraftClient (kirin.mixin.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (sodium.mixins.json)
		dlovin.inventoryhud.mixin.PlayerMixin (inventoryhud.mixins.json)
		de.maxhenkel.status.mixin.MinecraftMixin (status.mixins.json)
		de.guntram.mcmod.clickthrough.mixins.ItemUseMixin (mixins.clickthrough.json)
		de.keksuccino.fancymenu.mixin.client.MixinMinecraft (fancymenu.general.mixin.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		org.anti_ad.mc.ipnext.mixin.MixinMinecraftClient (mixins.ipnext.json)
		obro1961.chatpatches.mixin.MinecraftClientMixin (chatpatches.mixins.json)
		de.maxhenkel.peek.mixin.MinecraftMixin (peek.mixins.json)
		dev.stashy.extrasounds.mixin.hotbar.MinecraftClientMixin (extrasounds.mixins.json)
		dzwdz.chat_heads.mixin.MinecraftMixin (chat_heads.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		net.xolt.freecam.mixins.MinecraftClientMixin (freecam.mixins.json)
		de.johni0702.minecraft.bobby.mixin.MinecraftClientMixin (bobby.mixins.json)
	net.minecraft.client.main.Main:
		link.infra.screenshotclipboard.common.mixin.AWTHackMixin (screenshotclipboard-common.mixins.json)
`

**Comment by EGOIST1372** [comment]
This might be related to issue #24 

also here are all of my music/sound related mods:
AmbientSounds_FABRIC_v5.2.21_mc1.20.1
atmosfera-2.0.0+mc1.20
audioplayer-1.20.1-1.6.2
auudio_fabric_1.0.3_MC_1.20
cakechomps-fabric-6.1.0+1.20.1
extra-sounds-2.3.1+1.20.1~lonefelidae16-build.1
fm_audio_extension_fabric_1.1.1_MC_1.20
PresenceFootsteps-1.9.0
soundphysics-fabric-1.20.1-1.1.2
voicechat-fabric-1.20.1-2.4.19


some honorable mentions :D (these have some sound options):
make_bubbles_pop-0.1.1-1.19.4
chatpatches-201.5.5

**Comment by charlyb01** [comment]
I didn't reproduce with your mods, for the one I was able to find or test. Indeed, I wasn't able to find 1.20.1 version of Atmosfera and ExtraSounds, and I wasn't able to run AmbientSounds because the needed dependency to CreativeCore was preventing the game to launch. Where did you find those?

Your crash can be caused by another mod, even though it looks like the issue comes from my mod. Actually, my mod appears in the trace only because each time a music is played, it goes inside my code, but the bug is very unlikely to be caused by my mod. I'm afraid I can't help you more without more details.

**Comment by EGOIST1372** [comment]
atmosfera
https://github.com/Fourmisain/Atmosfera/releases/tag/2.0.0-1.20
extrasounds
https://github.com/lonefelidae16/extra-sounds/releases/tag/stable%2F1.20.1-build.1
ambientsound (the exact version u need to test)
https://www.curseforge.com/minecraft/mc-mods/ambientsounds/files/4693168
creative core
https://www.curseforge.com/minecraft/mc-mods/creativecore/files/4636842

hope it can help to find the problems

**Comment by charlyb01** [comment]
Hello, this was fixed recently! It was the same issue than the #38 one
