### ISSUE TITLE
Music Doesn't Add or Delete Properly

### ISSUE THREAD

**Issue by SmarterCob** [sf-inc/music_control#39]
Every time I remove or add music to a category/event inside the configure section, it doesn't save even after I click save.

**Comment by charlyb01** [comment]
Hello, did you enable the resource pack? The configuration is saved in it, and for now it's not enabling by itself on save.

**Comment by charlyb01** [comment]
If you could update me on your situation, this would be appreciated.  
Otherwise, I will consider that it's resolved and close the issue.

**Comment by SmarterCob** [comment]
Hi, sorry, I've been off Github for a bit
How do I enable it exactly?

**Comment by SmarterCob** [comment]
Nevermind, I know what you mean. I am having a different problem now though. For some odd reason, the custom music isn't working.

**Comment by charlyb01** [comment]
No problem.  
Is the music detected in the GUI? If yes, when clicking the music, you mean it's not playing? If not, did you ensure the hierarchy of your music files is correct?

**Comment by charlyb01** [comment]
Do not hesitate to check [this discussion](https://github.com/sf-inc/music_control/discussions/17). I recently added a "common mistakes" section that could be helpful 😉

**Comment by charlyb01** [comment]
Hi again! Please let me know if you still have an issue

**Comment by SmarterCob** [comment]
Oh my god, Hi, I am so sorry

**Comment by SmarterCob** [comment]
I just refound this

**Comment by SmarterCob** [comment]
No, it is not detected in the gui but it was a while ago so I can try again to see what happens

**Comment by charlyb01** [comment]
If it's not detected in the gui, it means your resource pack might not be loaded because of issues. Do not hesitate to check the link I sent you, it includes a common mistakes part
