### ISSUE TITLE
incorrect music in biomes when in servers

### ISSUE THREAD

**Issue by llenkha** [sf-inc/music_control#43]
I noticed when in servers the mod doesnt detect the biomes correctly yet still has the music in their category for their event like beaches and dark forests for example do not play anything in servers and is seen as empty events but in single player they work fine.

**Comment by charlyb01** [comment]
Hello, thanks for the report! That's interesting, I didn't notice. I will check that and get back to you

**Comment by llenkha** [comment]
Thanks, I noticed that in the files that there are no real vanilla music events for beaches or dark forests and i noticed that those are the biomes that are usually considered empty events in servers but in singleplayer they work fine

**Comment by charlyb01** [comment]
I can reproduce the bug, I will work on it
