### ISSUE TITLE
Add mute feature [request]

### ISSUE THREAD

**Issue by Qsta981** [sf-inc/music_control#46]
It would be nice if I could just mute music with one button press. Maybe add a keybind to mute and unmute music.

**Comment by charlyb01** [comment]
I released a new version that pause the music player when not playing music, so that if no music is playing, it won't play music later, as you would expect for a mute. Don't hesitate to try it out and tell me if that's enough in your opinion!

**Comment by Anoaxx** [comment]
maybe immidite mute would be a cool addition? :3

**Comment by charlyb01** [comment]
Immediate mute? Doesn't pausing music immediately "mute" the music? What do you mean exactly?

**Comment by charlyb01** [comment]
Hi again! Please let me know if current features are not sufficient for this request.

**Comment by Qsta981** [comment]
Sorry for accidentally closing it, but correct me if I am wrong, but I think music in the title menus still plays even when paused. It would be nice if there was a mute button just like on a computer.

**Comment by charlyb01** [comment]
If the title menus, you don't have access to keybinds, so you can't pause the music. However, if you pause the music in-game and go back to the title menus, music won't play again.

However, the purpose of the mod is to control how music is played in-game. I don't plan to add things in the title menus to control the music, even though I keep this idea on a sidenote as mentioned in #21. If that's the only thing missing from this issue, I will close it as I consider it out of scope of the mod, and I already keep one issue opened for title menu controls.
