### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by DonorKrovi** [sf-inc/music_control#48]
https://mclo.gs/TRPpbCD

**Comment by charlyb01** [comment]
Hello and thanks for the report! I will work on it very soon as I was going to release a new version.  
Could you tell me more about your issue, how did it happen? Were you manually changing music, is it the first music that tried to play, ... ?

**Comment by charlyb01** [comment]
I still would like to know the circumstances of your crash even though it must be already fixed
