### ISSUE TITLE
Custom Music

### ISSUE THREAD

**Issue by barraIhsan** [sf-inc/music_control#5]
Allow custom music also played So we can add custom sound since 1.15 maybe? So ALL custom music go to `assets/music/sounds/` so the namespace is `music`. And there is a new category (Like the NETHER, END, GAME, DiSC), the name is `CUSTOM`

TL;DR
Add New Category Called `CUSTOM` and it will contain all music in the `assets/music/sounds` (music defined in `assets/minecraft/sounds.json`)

**Comment by charlyb01** [comment]
I'm already working on this kind of thing for mods music but I got bugs during this that I'm trying to understand but it takes times (and I don't have a lot for modding). I'll see what I can do for custom music, I guess it's way easier. Stay updated but I have a lot to do already so not before 2 weeks I guess

**Comment by barraIhsan** [comment]
Its not mod, custom sound now possible in vanilla

**Comment by charlyb01** [comment]
I know, I told you it's two different things and I was already working on mods.... please take time to read what I write

**Comment by barraIhsan** [comment]
oh sorry

**Comment by charlyb01** [comment]
Could you send me a link of a tutorial of how to add music to minecraft? Can't find out, I just found how to replace existing one (whici is obviously already okay with my mod). Or if you have an example resource pack to share. Btw I assumed you were talking about adding musics via a resource pack, right?

**Comment by barraIhsan** [comment]
Yes, it by resourcepack, for example (the namespace is music, its just for separating them and also the song is undertake shop, idk why)
[Custom Music.zip](https://github.com/sf-inc/music_control/files/6255551/Custom.Music.zip)
Play it with `playsound music:undertale_shop master @s`
