### ISSUE TITLE
Add a way to display full length text

### ISSUE THREAD

**Issue by Krimatoria** [sf-inc/music_control#51]
Connector-1.0.0-beta.37+1.20.1.jar
music_control-1.6.2+1.20.1

It works in Play, but it doesn't work in Config

Could you make a setting so that the menu adapts to the width of the text? Or the full text was displayed when hovering over it. Sometimes it's not clear what kind of melody it is.
![image](https://github.com/sf-inc/music_control/assets/106809386/d835c8b2-bc25-408f-b637-626bdb9051ec)

**Comment by charlyb01** [comment]
Hello, you can add proper titles to your music in a resource pack if you want. Please see [here](https://github.com/sf-inc/music_control/discussions/17) for more information. But yes, I need to find a way to display longer texts in buttons. I will let you know if I find a way
