### ISSUE TITLE
Crash on 1.19.2 (fixed in later version)

### ISSUE THREAD

**Issue by S0ullessW0lf404** [sf-inc/music_control#53]
Hello, it seems that I've been encountering a client crash on my game that is related to this mod, **"apparently"** it happens only when I **change** **windows** either minimizing the game or just changing it directly when I'm inside of my world, I don't remember if it happens while playing normally, but I stick with the **1st option** just because the **2nd** one isn't that **common/doesn't happen**, this are the game, loader and mod versions:

**Game version: 1.19.2
Fabric version: 0.14.25
Mod version: [Beta] 1.6+1.19
World: Singleplayer**

I've seen a similar issue here but on the **1.20.1-server** with **fabric 0.14.22**, but since it was closed, I wasn't sure to mention the crash there, another thing is that the crash may be random, because there's sometimes it happens and sometimes not, but yesterday it happened twice with the **1st option** I said, I'll leave the crash log here if there's someting useful I can't see despite the lines that indicate the mod crashing the game.

[crash-2024-03-16_21.40.40-client.txt](https://github.com/sf-inc/music_control/files/14627931/crash-2024-03-16_21.40.40-client.txt)

**Comment by charlyb01** [comment]
Hello, this is indeed the same issue as #48.

This was fixed in version 1.7 of my mod. This version was not backported to older Minecraft version, so they still have the bug.  
If you really need the fix, I will see if I can backport it to 1.19.2, but I don't promise as it's quite old and may take time that I don't want to use that way.

**Comment by charlyb01** [comment]
Hi again, to port back to 1.19.2, I would need to undo too many changes. So, I'm not going to backport the fix to 1.19.2 sorry

**Comment by S0ullessW0lf404** [comment]
Hi, well that's a bit sad, but understandable, knowing the big work that is present on backporting to previous versions, at least I confirmed the crash isn't present anymore on later versions because if I'm not wrong there's a previous version of the mod for the 1.20 [1.6.2-1.6.4] version of the game in wich I saw the crash was present on, thing that I wasn't sure if it was fixed in those version of the mod you said.

Thanks for your attention and explaining, good luck with the mod.
