### ISSUE TITLE
add disc to history?

### ISSUE THREAD

**Issue by alien-sunset** [sf-inc/music_control#56]
i know this mod is mostly for the in game background music, but is it possible to add played music discs to the history?
the game has to send that info to the player so my game knows what to play when a disc is inserted, so it should be detectable by the mod, right?

**Comment by charlyb01** [comment]
Hello, it's actually quite different, but I could add it. However, I don't really see the interest in this, unless you would add several music to a single disc. Also, as I'm not going to add controls to music disc (like pause etc), this would be a bit inconsistent to have the history of the music disc. Is there any particular reason you would like this feature?

**Comment by alien-sunset** [comment]
mostly with the new jukebox automation, a couple of people on my server have constantly playing disks at their bases, which i don't mind, i can pause my bg music, so it doesn't interfere, but i have it set so i can hear disc music as bg music too... but since jukebox music isn't listed in the history i often end up hearing the same song really close together, and occasionally twice in a row, so having it listed in the history would help fix that.

it's not a huge deal, and i'm sure i'm probably a niche case, but thought it couldn't hurt to ask.

**Comment by charlyb01** [comment]
Oh I understand the use case now. What I was thinking was more like a separate history for music disc, as they are handled in two different canals, but in your case, I guess you were thinking of a mix of sounds history. This can't really be done, as bg music is in background, while music disc are played in the world at a specific position. And if it's twice the same music disc (without more than one music in a disc), I can't change the disc, as it's handled by the dispenser logic. As this mod is is client-side, I don't update the server logic.

**Comment by alien-sunset** [comment]
well, yeah you wouldn't be able to change the in world jukebox music, so i know I'm still sometimes going to hear say, cat in my bg via the mod and then go to my friends base and hear it on their jukebox too.

what I'm looking for is the other way around, if I hear cat on my friend's jukebox, ant then it won't come up in my bg music until it gets pushed out of the history

**Comment by charlyb01** [comment]
Oh once again I didn't think of this case! Well I guess you're playing "ALL" category, that contains disc music too. I can indeed add music played by disc in the history then. I'll update you when I'll work on it. I'm currently working on the mod, so it may be soon

**Comment by alien-sunset** [comment]
oh, awesome! thank you!
this is already such a great mod, I really appreciate it 😄
