### ISSUE TITLE
v1.8+1.20.6 requires Fabric Loader 0.15.11

### ISSUE THREAD

**Issue by GeneralMint** [sf-inc/music_control#57]
I am having an issue trying to get MC launched with this mod. In the logs the game seems to stop when checking for updates? And this only happens when I have Music Control applied in the apps content menu. When I check it off, Minecraft launches totally fine. Or is there a possible mod conflict that I am missing.
I am playing on MC version 1.20.6 and the Fabric loader 0.15.10. 

[Pastebin link for the logs here](https://pastebin.com/XB8pTHDZl)
I am sorry if this issue is a completely different problem, I am just unsure where to start

**Comment by charlyb01** [comment]
Hi, thanks for the report! Your link has already expired, I can't look at the logs.

**Comment by charlyb01** [comment]
Hi again, without your log, I can already tell you the problem, as someone had the same on my [Discord](https://discord.gg/eNwkve8k7c) server. You need to use the **Fabric Loader 0.15.11**. I didn't notice that LibGUI (integrated in my mod) required it.

**Comment by GeneralMint** [comment]
Ah of course, got it working fine now on that fabric version. Sorry for the bother.
**Fabric Loader0.15.11** is what you need for anyone else. :)
