### ISSUE TITLE
Night music isn't playing

### ISSUE THREAD

**Issue by servalfan531** [sf-inc/music_control#58]
Just what it says in the title. I've got songs added to the night music event, but they never play randomly or from skipping to the next song. Clicking on the Night Time event button in the menu will play the music though. It just seems like the event never triggers in-game, even though I'm pretty sure my configs should enable it. Any help would be appreciated. Thank you!

**Comment by charlyb01** [comment]
Hi, thanks for the report! This is indeed a bug I didn't notice. I will release a bug fix soon
