### ISSUE TITLE
The game just dosen't load

### ISSUE THREAD

**Issue by GamingProX66** [sf-inc/music_control#59]
When i add the mod to my mods folder the game just dosen't load like , AT ALL

**Comment by charlyb01** [comment]
Hi, thanks for the report but I'll need way more details. 

What's your Minecraft version, Music Control version?  
Are you playing with other mods (surely), did you try to remove some, run the game with my mod only, ... ?

**Comment by charlyb01** [comment]
Hi, do you still have your issue? Without further information from you, I will close this issue
