### ISSUE TITLE
Game immediately crashes when trying to use Music_control.

### ISSUE THREAD

**Issue by Beaudoggy** [sf-inc/music_control#62]
My game will immediately crashes when trying to use Music control Mod, the error I get in the crash logs is ,

at net.minecraft.class_1142.handler$cap000$music_control$playMusic(class_1142.java:573)
at net.minecraft.class_1142.method_4858(class_1142.java).

**Comment by CuriousCodingCanadian** [comment]
You didn't provide the error...

**Comment by charlyb01** [comment]
Hi, thanks for the report. I'll need more information like the minecraft and mod versions. Also, the complete log file would be better to understand your issue
